#!/bin/bash
arg="${1:-}"
case "$arg" in
  --Speakers)
    SINK="alsa_output.pci-0000_09_00.4.analog-stereo"
    pacmd set-default-sink "$SINK"
    pacmd list-sink-inputs | grep index | while read line; do
      pacmd move-sink-input `echo $line | cut -f2 -d' '` "$SINK"
    done
    echo "Speakers" > $HOME/Scripts/audio_switch/active_audio_device
    ;;
  --Headphones)
    SINK="alsa_output.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FiiO_USB_DAC-E10-00.analog-stereo"
    pacmd set-default-sink "$SINK"
    pacmd list-sink-inputs | grep index | while read line; do
      pacmd move-sink-input `echo $line | cut -f2 -d' '` "$SINK"
    done
    echo "Headphones" > $HOME/Scripts/audio_switch/active_audio_device
    ;;
  *)
    # Setting this as the default lets polybar call the script and display
    # an icon of some sort on the icon bar. The character I used isn't
    # showing up right on this non-linux machine I'm using, so replace "X"
    # with whatever character or symbol you want on your polybar.
    cat $HOME/Scripts/audio_switch/active_audio_device
    ;;
esac
